# Generated by Django 2.0.7 on 2018-07-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_ru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeru',
            name='paragraph2',
            field=models.TextField(default='test2'),
        ),
        migrations.AddField(
            model_name='homeru',
            name='paragraph3',
            field=models.TextField(default='test3'),
        ),
        migrations.AddField(
            model_name='homeru',
            name='paragraph4',
            field=models.TextField(default='test4'),
        ),
        migrations.AlterField(
            model_name='homeru',
            name='paragraph1',
            field=models.TextField(default='test1'),
        ),
    ]
