# Generated by Django 2.0.7 on 2018-07-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_ru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph12',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph13',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='paragraph9',
            field=models.TextField(blank=True),
        ),
    ]
