# Generated by Django 2.0.7 on 2018-07-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_ru', '0002_auto_20180726_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innerhomeru',
            old_name='h2',
            new_name='h1',
        ),
    ]
