# Generated by Django 2.0.7 on 2018-07-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_ru', '0002_auto_20180723_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeru',
            options={'verbose_name_plural': 'Home page ru'},
        ),
    ]
