# Generated by Django 2.0.7 on 2018-08-17 07:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_ru', '0003_auto_20180726_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAssesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_doc_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=80)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('marital_status', models.CharField(choices=[('0', 'Выбрать...'), ('1', 'Брак аннулирован'), ('2', 'Гражданский брак'), ('3', 'В разводе / Separated'), ('4', 'Legally Separated'), ('5', 'В браке'), ('6', 'Never Married / Single/ Холост'), ('7', 'Вдовец / вдова')], default='0', max_length=22)),
                ('country', models.CharField(default='_', max_length=45)),
                ('dob', models.DateField()),
                ('immigration_status', models.CharField(choices=[('0', 'Выбрать...'), ('1', 'Not Applicable'), ('2', 'Гость'), ('3', 'Student'), ('4', 'Worker')], default='0', error_messages={'invalid': 'Waehlen Sie die Zahlungsart!', 'required': 'Waehlen Sie die Zahlungsart!'}, max_length=14)),
                ('edu_level', models.CharField(choices=[('0', 'Выбрать...'), ('1', 'None, or less then secondary (high school)'), ('2', 'Secondary diploma (High school Diploma)'), ('3', 'One-year program at a university, college, trade or technical school, or other institute'), ('4', 'Two-year program at a university, college, trade or technical school, or other institute'), ('5', "Bachelor's degree (three or more year program at a university, college, trade or technical school, or other institute)"), ('6', 'Two or more certificates, diplomas, or degrees. One must be for a program of three or more years'), ('7', "Master's degree, or professional degree needed to practice in a licensed profession"), ('8', 'Doctoral level university degree (PhD)')], default='0', max_length=118)),
                ('canadian_dipl', models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], default='N', max_length=3)),
                ('school_progr_name', models.TextField(blank=True, max_length=80)),
                ('off_lang_en', models.CharField(max_length=40)),
                ('off_lang_fr', models.CharField(max_length=40)),
                ('work_exp_canada', models.TextField(max_length=120)),
                ('canadian_cert', models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], default='N', max_length=3)),
                ('valid_job', models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], default='N', max_length=3)),
                ('nomin_cert', models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], default='N', max_length=3)),
                ('partner_status_of_canada', models.CharField(choices=[('NO', 'None'), ('Y', 'Да'), ('N', 'Нет')], default='NO', max_length=3)),
                ('partner_track', models.CharField(choices=[('NO', 'None'), ('Y', 'Да'), ('N', 'Нет')], default='NO', max_length=3)),
                ('partner_edu', models.CharField(choices=[('0', 'Выбрать...'), ('1', 'None, or less then secondary (high school)'), ('2', 'Secondary diploma (High school Diploma)'), ('3', 'One-year program at a university, college, trade or technical school, or other institute'), ('4', 'Two-year program at a university, college, trade or technical school, or other institute'), ('5', "Bachelor's degree (three or more year program at a university, college, trade or technical school, or other institute)"), ('6', 'Two or more certificates, diplomas, or degrees. One must be for a program of three or more years'), ('7', "Master's degree, or professional degree needed to practice in a licensed profession"), ('8', 'Doctoral level university degree (PhD)')], default='0', max_length=118)),
                ('partner_work_exp', models.TextField(blank=True, max_length=120)),
                ('partner_lang', models.CharField(blank=True, max_length=40)),
                ('sibling_in_canada', models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], default='N', max_length=3)),
                ('memo', models.TextField(blank=True)),
            ],
        ),
    ]
