# Generated by Django 2.0.7 on 2018-07-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_ru', '0003_auto_20180723_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeru',
            options={'verbose_name_plural': 'Home_page_ru'},
        ),
    ]
