# Generated by Django 2.0.7 on 2018-08-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_ru', '0006_auto_20180820_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassesment',
            name='partner_edu',
            field=models.CharField(choices=[('0', 'Выбрать...'), ('1', 'None, or less then secondary (high school)'), ('2', 'Secondary diploma (High school Diploma)'), ('3', 'One-year program at a university, college, trade or technical school, or other institute'), ('4', 'Two-year program at a university, college, trade or technical school, or other institute'), ('5', "Bachelor's degree (three or more year program at a university, college, trade or technical school, or other institute)"), ('6', 'Two or more certificates, diplomas, or degrees. One must be for a program of three or more years'), ('7', "Master's degree, or professional degree needed to practice in a licensed profession"), ('8', 'Doctoral level university degree (PhD)')], default='1', max_length=118),
        ),
    ]
