# Generated by Django 2.0.7 on 2018-08-30 07:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_ru', '0012_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassesment',
            name='immigration_status',
            field=models.CharField(choices=[('0', 'Выбрать...'), ('1', 'Туристическая'), ('2', 'Студенческая'), ('3', 'Рабочая'), ('4', 'Нет')], default='0', max_length=14),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='marital_status',
            field=models.CharField(choices=[('0', 'Выбрать...'), ('1', 'Брак признан недействительным'), ('2', 'В гражданском браке'), ('3', 'В разводе'), ('4', 'Не в браке'), ('5', 'В браке'), ('6', 'Вдовец / вдова')], default='0', max_length=22),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='off_lang_en_level',
            field=models.CharField(choices=[('0', 'Выбрать...'), ('1', 'Не владею'), ('2', 'Начальный'), ('3', 'Средний'), ('4', 'Выше среднего'), ('5', 'Свободное')], default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='off_lang_fr_level',
            field=models.CharField(choices=[('0', 'Выбрать...'), ('1', 'Не владею'), ('2', 'Начальный'), ('3', 'Средний'), ('4', 'Выше среднего'), ('5', 'Свободное')], default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_level',
            field=models.CharField(choices=[('0', 'Выбрать...'), ('1', 'Среднее'), ('2', 'Среднее специальное'), ('3', 'Высшее'), ('4', 'Бакалавриат'), ('5', 'Аспирантура / Докторантура')], default='0', max_length=118),
        ),
        migrations.AlterField(
            model_name='education',
            name='int_program',
            field=models.CharField(choices=[('0', 'Выбрать...'), ('1', 'Курсы английского языка'), ('2', 'Курсы французского языка'), ('3', 'Каникулярные программы для детей и подростков'), ('4', 'Среднее образование'), ('5', 'Подготовка к поступлению в вуз'), ('6', 'Высшее образование'), ('7', 'Последипломное образование'), ('8', 'Магистратура'), ('9', 'Докторантура')], default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='education',
            name='marital_status',
            field=models.CharField(choices=[('0', 'Выбрать...'), ('1', 'В браке'), ('2', 'В гражданском браке'), ('3', 'Не в браке')], default='0', max_length=22),
        ),
        migrations.AlterField(
            model_name='homeru',
            name='paragraph2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homeru',
            name='paragraph3',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
