# Generated by Django 2.0.7 on 2018-08-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_ru', '0013_auto_20180830_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innerhomeru',
            name='body',
        ),
        migrations.AlterField(
            model_name='homeru',
            name='paragraph1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homeru',
            name='paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homeru',
            name='paragraph3',
            field=models.TextField(blank=True),
        ),
    ]
