# Generated by Django 2.0.7 on 2018-10-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_ru', '0014_auto_20180830_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innerhomeru',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
