# Generated by Django 2.0.7 on 2018-11-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_ru', '0017_auto_20181113_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeru',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeru',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
