# Generated by Django 2.0.7 on 2018-07-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('h1', models.CharField(blank=True, max_length=30)),
                ('paragraph1', models.TextField(blank=True)),
                ('paragraph2', models.TextField(blank=True)),
                ('paragraph3', models.TextField(blank=True)),
                ('paragraph4', models.TextField(blank=True)),
                ('paragraph5', models.TextField(blank=True)),
                ('paragraph6', models.TextField(blank=True)),
                ('paragraph7', models.TextField(blank=True)),
                ('paragraph8', models.TextField(blank=True)),
                ('paragraph9', models.TextField(blank=True)),
                ('paragraph10', models.TextField(blank=True)),
                ('paragraph11', models.TextField(blank=True)),
                ('paragraph12', models.TextField(blank=True)),
                ('paragraph13', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='InnerHomeEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('h1', models.CharField(blank=True, max_length=30)),
                ('paragraph1', models.TextField(blank=True)),
                ('paragraph2', models.TextField(blank=True)),
                ('paragraph3', models.TextField(blank=True)),
                ('paragraph4', models.TextField(blank=True)),
                ('paragraph5', models.TextField(blank=True)),
                ('paragraph6', models.TextField(blank=True)),
                ('paragraph7', models.TextField(blank=True)),
                ('paragraph8', models.TextField(blank=True)),
                ('paragraph9', models.TextField(blank=True)),
                ('paragraph10', models.TextField(blank=True)),
                ('paragraph11', models.TextField(blank=True)),
                ('paragraph12', models.TextField(blank=True)),
                ('paragraph13', models.TextField(blank=True)),
                ('outer_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp_en.HomeEn')),
            ],
            options={
                'verbose_name_plural': 'Nested Pages',
            },
        ),
    ]
