# Generated by Django 2.0.7 on 2018-07-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0003_clientassesment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassesment',
            name='canadian_dipl',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='dob',
            field=models.DateField(help_text='Please use the following format: <em>dd.mm.yyyy</em>.'),
        ),
    ]
