# Generated by Django 2.0.7 on 2018-07-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0004_auto_20180729_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassesment',
            name='canadian_dipl',
            field=models.BooleanField(),
        ),
    ]
