# Generated by Django 2.0.7 on 2018-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0005_auto_20180729_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassesment',
            name='canadian_dipl',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10),
        ),
    ]
