# Generated by Django 2.0.7 on 2018-07-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0006_auto_20180729_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassesment',
            name='name',
            field=models.CharField(default='', max_length=35),
        ),
    ]
