# Generated by Django 2.0.7 on 2018-07-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0009_auto_20180730_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassesment',
            name='canadian_cert',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='canadian_dipl',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='nomin_cert',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='partner_status_of_canada',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='partner_track',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='sibling_in_canada',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='valid_job',
            field=models.BooleanField(),
        ),
    ]
