# Generated by Django 2.0.7 on 2018-07-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0011_auto_20180730_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassesment',
            name='canadian_cert',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')]),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='canadian_dipl',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')]),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='edu_level',
            field=models.CharField(choices=[('1', 'None, or less then secondary (high school)'), ('2', 'Secondary diploma (High school Diploma)'), ('3', 'One-year program at a university, college, trade or technical school, or other institute'), ('4', 'Two-year program at a university, college, trade or technical school, or other institute'), ('5', "Bachelor's degree (three or more year program at a university, college, trade or technical school, or other institute)"), ('6', 'Two or more certificates, diplomas, or degrees. One must be for a program of three or more years'), ('7', "Master's degree, or professional degree needed to practice in a licensed profession"), ('8', 'Doctoral level university degree (PhD)')], default='1', max_length=118),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='immigration_status',
            field=models.CharField(choices=[('1', 'Not Applicable'), ('2', 'Visitor'), ('3', 'Student'), ('4', 'Worker')], default='1', max_length=14),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='marital_status',
            field=models.CharField(choices=[('1', 'Annulled Marriage'), ('2', 'Common-Law'), ('3', 'Divorced / Separated'), ('4', 'Legally Separated'), ('5', 'Married'), ('6', 'Never Married / Single'), ('7', 'Widowed')], default='6', max_length=22),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='nationality',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='nomin_cert',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')]),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='partner_status_of_canada',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')]),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='partner_track',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')]),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='sibling_in_canada',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')]),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='valid_job',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')]),
        ),
    ]
