# Generated by Django 2.0.7 on 2018-07-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0016_auto_20180731_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassesment',
            name='canadian_cert',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='canadian_dipl',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='nomin_cert',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='partner_status_of_canada',
            field=models.CharField(choices=[('NO', 'None'), ('Y', 'Yes'), ('N', 'No')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='partner_track',
            field=models.CharField(choices=[('NO', 'None'), ('Y', 'Yes'), ('N', 'No')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='school_progr_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='sibling_in_canada',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='valid_job',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3),
        ),
    ]
