# Generated by Django 2.0.7 on 2018-08-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0019_auto_20180815_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientassesment',
            name='work_exp_home',
        ),
        migrations.AddField(
            model_name='clientassesment',
            name='country',
            field=models.CharField(default='_', max_length=45),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='address',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='partner_work_exp',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='school_progr_name',
            field=models.TextField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='work_exp_canada',
            field=models.TextField(max_length=120),
        ),
    ]
