# Generated by Django 2.0.7 on 2018-08-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0020_auto_20180817_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassesment',
            name='country',
            field=models.CharField(max_length=45),
        ),
    ]
