# Generated by Django 2.0.7 on 2018-08-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0021_auto_20180817_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassesment',
            name='partner_status_of_canada',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='clientassesment',
            name='partner_track',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3),
        ),
    ]
