# Generated by Django 2.0.7 on 2018-08-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0024_auto_20180820_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientassesment',
            name='off_lang_en',
        ),
        migrations.RemoveField(
            model_name='clientassesment',
            name='off_lang_fr',
        ),
        migrations.AddField(
            model_name='clientassesment',
            name='off_lang_en_level',
            field=models.CharField(choices=[('0', 'Please Choose...'), ('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced'), ('4', 'Fluent')], default='0', max_length=15),
        ),
        migrations.AddField(
            model_name='clientassesment',
            name='off_lang_fr_level',
            field=models.CharField(choices=[('0', 'Please Choose...'), ('1', 'Not applicable'), ('2', 'Beginner'), ('3', 'Intermediate'), ('4', 'Advanced'), ('5', 'Fluent')], default='0', max_length=15),
        ),
    ]
