# Generated by Django 2.0.7 on 2018-08-30 07:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0026_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeen',
            name='paragraph1',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homeen',
            name='paragraph2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homeen',
            name='paragraph3',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
