# Generated by Django 2.0.7 on 2018-10-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0029_auto_20181008_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeen',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innerhomeen',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
