# Generated by Django 2.0.7 on 2018-11-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_en', '0030_auto_20181031_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeen',
            name='h1',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='innerhomeen',
            name='h1',
            field=models.CharField(blank=True, max_length=33),
        ),
    ]
